public enum Partidos {
    PDT, PT, PTB, PMDB, DEM, PCB, PSB, PSDB, PTC, PSC, PMN, PRP, PPS, PV, AVANTE, PP, PSTU, PRTB, PHS, 
    PSDC, PCO, PODE, PSL, PRB, PSOL, PR, PPL, PEN, PROS, SD, NOVO, REDE, PMB;
}
